dist: trusty
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache/files


env:
  global:
    # For functional tests
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"

matrix:
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: CHECK_CS=true
        - php: 7.2
        # Functional
        - php: 5.6
          env: BEHAT_OPTS="--profile=rest --tags=~@broken --suite=fullJson" EZPLATFORM_BRANCH=1.13 SYMFONY_ENV=behat PHP_IMAGE=ezsystems/php:5.6-v1
        - php: 7.1
          env: BEHAT_OPTS="--profile=rest --tags=~@broken --suite=fullJson" EZPLATFORM_BRANCH=2.0 SYMFONY_ENV=behat

# test only master (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - travis_retry composer selfupdate
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "$BEHAT_OPTS" = "" ] ; then travis_retry composer install --prefer-dist --no-interaction ; fi
    - if [ "$BEHAT_OPTS" != "" ] ; then ./tests/.travis/prepare_for_functional_tests.sh ; fi

script:
    - if [ "$BEHAT_OPTS" = "" ] ; then php vendor/bin/phpunit --coverage-text && php vendor/bin/phpspec run --format=pretty ; fi
    - if [ "$BEHAT_OPTS" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/behat $BEHAT_OPTS" ; fi
    - if [ "$CHECK_CS" = "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false
